// <auto-generated />
using System;
using System.Text.Json;
using CultivationApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CultivationApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722145306_UpdateServerConfigChatToEarn")]
    partial class UpdateServerConfigChatToEarn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CultivationApi.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CultivationApi.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CurrentQi")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DailyQiAccumulated")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastMeditated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumericLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SpiritStones")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId");

                    b.HasIndex("ServerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("CultivationApi.Domain.Entities.DiscordUser", b =>
                {
                    b.Property<string>("DiscordId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DiscordId");

                    b.ToTable("DiscordUsers");
                });

            modelBuilder.Entity("CultivationApi.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("CultivationApi.Domain.Entities.ServerConfig", b =>
                {
                    b.Property<string>("ServerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ChatToEarnChannels")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("DailyQiLimit")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MessageCooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("QiPerMessage")
                        .HasColumnType("integer");

                    b.Property<string>("RealmNames")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ServerId");

                    b.ToTable("ServerConfigs");
                });

            modelBuilder.Entity("CultivationApi.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("CultivationApi.Domain.Entities.Character", "Character")
                        .WithMany("AuditLogs")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("CultivationApi.Domain.Entities.Character", b =>
                {
                    b.HasOne("CultivationApi.Domain.Entities.DiscordUser", "DiscordUser")
                        .WithMany("Characters")
                        .HasForeignKey("DiscordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CultivationApi.Domain.Entities.ServerConfig", "ServerConfig")
                        .WithMany("Characters")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CultivationApi.Domain.Entities.BaseStats", "BaseStats", b1 =>
                        {
                            b1.Property<Guid>("CharacterId");

                            b1.Property<int>("Agility");

                            b1.Property<int>("Health");

                            b1.Property<int>("Luck");

                            b1.Property<int>("Mana");

                            b1.Property<int>("Strength");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters");

                            b1
                                .ToJson("BaseStats")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("BaseStats")
                        .IsRequired();

                    b.Navigation("DiscordUser");

                    b.Navigation("ServerConfig");
                });

            modelBuilder.Entity("CultivationApi.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("CultivationApi.Domain.Entities.Character", "Character")
                        .WithOne("Inventory")
                        .HasForeignKey("CultivationApi.Domain.Entities.Inventory", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CultivationApi.Domain.Entities.EquippedGear", "EquippedGear", b1 =>
                        {
                            b1.Property<Guid>("InventoryId");

                            b1.Property<string>("Artifact");

                            b1.Property<string>("Chest");

                            b1.Property<string>("Head");

                            b1.Property<string>("Weapon");

                            b1.HasKey("InventoryId");

                            b1.ToTable("Inventories");

                            b1
                                .ToJson("EquippedGear")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.Navigation("Character");

                    b.Navigation("EquippedGear")
                        .IsRequired();
                });

            modelBuilder.Entity("CultivationApi.Domain.Entities.Character", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("CultivationApi.Domain.Entities.DiscordUser", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("CultivationApi.Domain.Entities.ServerConfig", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
